### Comandos básicos

In [1]:
# Saludo #1
print("Hello, World!")

Hello, World!


In [2]:
# Saludo #2
var = "Hello, World!"
print(var)

Hello, World!


In [3]:
# Suma
5 + 3


# Resta
5 - 3


# Multiplicación
5 * 3


# División
5 / 3


# Floor division
5 // 3


# Módulo 
5 % 3


# Potencia
5 ** 3

125

In [4]:
# Condicional if
a = 42
b = 3.1416
if b > a:
  print("b es mayor a a")
elif a == b:
  print("a y b son iguales")
else:
  print("a es mayor a b")

a es mayor a b


In [5]:
fruits = ["manzana", "pera", "mora"]
adj = ["roja", "verde", "azul"]

for x in fruits:
    for y in adj:
        print(x, y)

manzana roja
manzana verde
manzana azul
pera roja
pera verde
pera azul
mora roja
mora verde
mora azul


In [6]:
# Importar librerías (ya instaladas)
import numpy as np
import pandas as pd

In [7]:
data = {'year': [2010, 2011, 2012,
                 2010, 2011, 2012,
                 2010, 2011, 2012],
        'team': ['FCBarcelona', 'FCBarcelona',
                 'FCBarcelona', 'RMadrid',
                 'RMadrid', 'RMadrid',
                 'ValenciaCF', 'ValenciaCF',
                 'ValenciaCF'],
        'wins': [30, 28, 32, 29, 32, 26, 21, 17, 19],
        'draws': [6, 7, 4, 5, 4, 7, 8, 10, 8],
        'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11]
       }
football = pd.DataFrame(data, 
                        columns = ['year', 'team', 'wins', 'draws', 'losses'])
football.head()

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2

In [8]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [9]:
print(a.shape)
print(a.dtype.name)
print(type(a))

(3, 5)
int64
<class 'numpy.ndarray'>


### Ejercicios

1. Escribe una función que dado un string s y un entero no negativo n regrese n copias de s. 
2. Escribe una función que dado un arreglo de números revise si el producto de dos números del arreglo es par.
3. Escribe una función que dado un arreglo con valores None regrese el arreglo con los valores None reemplazados por el valor no None anterior en el arreglo.
4. Escribe una función que dada una lista regrese la misma lista ordenada. 