# Introducción a NumPy

#### **NumPy es el paquete fundamental para la computación científica en Python.**

NumPy es una biblioteca de Python que proporciona un objeto de matriz n-dimensional (`ndarray`) de tipos de datos homogéneos, varios objetos derivados y una variedad de rutinas para operaciones rápidas en matrices.

### ¿Cuál es la diferencia entre las matrices NumPy (`ndarray`) y las secuencias estándar de Python?

Las diferencias más importantes entre las matrices NumPy (`ndarray`) y las secuencias estándar de Python son las siguientes:
* Las matrices NumPy tienen un tamaño fijo en la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Cambiar el tamaño de un `ndarray` creará una nueva matriz y eliminará la original.
* Se requiere que todos los elementos en una matriz NumPy sean del mismo tipo de datos y, por lo tanto, tendrán el mismo tamaño en la memoria. La excepción: uno puede tener matrices de objetos (Python, incluido NumPy), lo que permite matrices de elementos de diferentes tamaños.
* Las matrices NumPy facilitan operaciones matemáticas avanzadas y de otro tipo en grandes cantidades de datos. Por lo general, tales operaciones se ejecutan de manera más eficiente y con menos código de lo que es posible con las secuencias integradas de Python.
* Una plétora creciente de paquetes científicos y matemáticos basados en Python está utilizando matrices NumPy; aunque estos suelen admitir la entrada de secuencia de Python, convierten dicha entrada en matrices NumPy antes del procesamiento y, a menudo, generan matrices NumPy. En otras palabras, para usar de manera eficiente gran parte (quizás incluso la mayoría) del software científico/matemático actual basado en Python, no basta con saber cómo usar los tipos de secuencia integrados de Python; también es necesario saber cómo usar las matrices NumPy.

### ¿Por qué NumPy es rápido?

La vectorización y el broadcasting. 

La vectorización del código describe la ausencia de bucles explícitos, indexación, etc., en el código a pesar de que  "detrás de escena" la ejecució corre en código C optimizado y precompilado. El código vectorizado tiene muchas ventajas, entre las que se encuentran:
* Es más conciso y más fácil de leer. 
* Requiere de menos líneas de código, lo que generalmente significa menos errores. 
* Se parece más a la notación matemática estándar (lo que facilita, por lo general, codificar correctamente las construcciones matemáticas). 
* Da como resultado código más "pythonic". Sin la vectorización, nuestro código estaría plagado de bucles difíciles de leer e ineficientes.

El broadcasting es el término utilizado para describir el comportamiento implícito de las operaciones elemento por elemento. En términos generales, en NumPy todas las operaciones se comportan de esta manera. 

## Importación y otros comandos útiles

Por convención, NumPy se importa con el alias *np*.

In [1]:
import numpy as np

In [2]:
# Imprime versión de numpy
np.__version__

'1.21.5'

In [3]:
# Imprime documentación bult-in de numpy
np?

## Las variables son más que solo su valor

Una de las ventajas mayormente reconocidas de Python es que es un lenguaje de programación que se tipifica dinámicamente. Mientras que un lenguaje de programación de tipo estático como C o Java requiere que cada variable se declare explícitamente, un lenguaje de programación de tipo dinámico como Python omite esta especificación.

In [4]:
# Código en Python
x = 4
x = "four"

Comprender cómo funciona esto es esencial cuando se busca aprender a analizar datos de manera eficiente y efectiva con Python. La flexibilidad que otorga un lenguaje de programación de tipo dinámico sugiere que las variables de Python son más que solo su valor pues también contienen información adicional sobre el tipo de valor.

La implementación estándar de Python está escrita en C. Esto significa que cada objeto de Python es una estructura C, que contiene no solo su valor, sino también otra información. Por ejemplo, cuando definimos un número entero en Python, como `x = 10000`, `x` no es solo un número entero per se, y en realidad, es un puntero a una estructura C compuesta, que contiene varios valores como el recuento de referencias que ayuda a Python a manejar silenciosamente la asignación y desasignación de memoria, el tipo de la variable, el tamaño de la variable y el valor entero real que esperamos que represente la variable de Python.

La información adicional en la estructura de datos de Python es lo que permite que Python se codifique de manera tan libre. Sin embargo, la información adicional en los tipos de Python tiene un costo, que se vuelve especialmente evidente en las estructuras que combinan muchos de estos objetos.

El contenedor multielemento mutable estándar en Python es la lista.

In [5]:
# Declara lista (l) con una secuencia lineal de los primeros 10 enteros consecutivos
l = list(range(10))

# Imprime lista l
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
# Devuelve tipo de lista l
type(l)

list

In [7]:
# Devuelve tipo del primer elemento de lista l
type(l[0])

int

In [8]:
# Declara lista (l2) con una secuencia lineal de los primeros 10 enteros consecutivos como strings
l2 = [str(i) for i in l]

# Imprime lista l2
print(l2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [9]:
# Devuelve tipo de lista l2
type(l2)

list

In [10]:
# Devuelve tipo del primer elemento de lista l2
type(l[0])

int

In [11]:
# Declara lista (l3) con valores de tipos distintos
l3 = [42, 42.0, "42", True]

# Imprime lista l3
print(l3)

[42, 42.0, '42', True]


In [12]:
# Devuelve tipo de todos los elementos de la lista l3
[type(i) for i in l3]

[int, float, str, bool]

Cada elemento de una lista debe contener su propia información pues cada uno es un objeto de Python completo. En el caso de que todas las variables sean del mismo tipo, mucha de esta información es redundante. Por ello, resulta mucho más eficiente almacenar datos en un arreglo o una matriz de tipo fijo, es decir, un `ndarray`.

## Creando un `ndarray`

### A partir de una lista

`np.array` permite crear arreglos a partir de una lista.

In [13]:
# Declara arreglo de enteros
np.array([2, 3, 5, 7, 11])

array([ 2,  3,  5,  7, 11])

Si los tipos de un arreglo no coinciden, NumPy ejecutará un upcast si es posible.

In [14]:
# Declara arreglo con valores de tipos distintos
np.array([2, 3.1416, 5, 7, 11])

array([ 2.    ,  3.1416,  5.    ,  7.    , 11.    ])

Si queremos establecer explícitamente el tipo de datos del arreglo resultante, podemos usar el parámetro `dtype`.

In [15]:
# Declara arreglo de flotantes
np.array([2, 3, 5, 7, 11], dtype='float32')

array([ 2.,  3.,  5.,  7., 11.], dtype=float32)

A diferencia de las listas de Python, los arreglos NumPy pueden ser explícitamente multidimensionales, es decir, las listas internas se tratan como filas del arreglo bidimensional (o matriz) resultante.

In [16]:
# Declara matriz 3x3
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Desde 0

Especialmente para arreglos más grandes, es más eficiente crear arreglos o matrices desde cero utilizando rutinas integradas en NumPy.

In [17]:
# Declara arreglo con una secuencia linear en el intervalo [0, 30), de 5 en 5
np.arange(0, 30, 5)

array([ 0,  5, 10, 15, 20, 25])

In [18]:
# Declara arreglo de tamaño 42 de ceros enteros
np.zeros(42, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
# Declara matriz 6x12 de unos de flotantes
np.ones((6, 12), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
# Declara arreglo de tamaño 2x10 del valor 42
np.full((2, 10), 42)

array([[42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42]])

In [21]:
# Declara arreglo de 5 valores espaciados uniformemente en el intervalo [0, 10]
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
# Delcara matriz 4x4 de valores aleatorios entre 0 y 1
np.random.random((4, 4))

array([[0.77549742, 0.18228215, 0.70203673, 0.94957269],
       [0.01692847, 0.0974865 , 0.01279715, 0.60604888],
       [0.97478219, 0.94242096, 0.80757835, 0.93187696],
       [0.88105279, 0.45352808, 0.35171375, 0.61306066]])

In [23]:
# Delcara matriz 4x4 de valores aleatorios normalmente distribuidos con media de 0 y desviación estándar de 1
np.random.normal(0, 1, (4, 4))

array([[-0.19733948,  1.31878451, -0.0801891 ,  0.03726215],
       [ 0.04799027, -1.06735974, -0.23567432, -1.11595108],
       [-0.18027436, -0.43249147,  0.05777055,  0.51184385],
       [-0.63377361, -0.94077983, -0.49376983, -2.06858655]])

In [24]:
# Delcara matriz 4x4 de valores aleatorios en el intervalo [0, 10)
np.random.randint(0, 10, (4, 4))

array([[0, 3, 2, 9],
       [0, 7, 5, 3],
       [0, 3, 0, 0],
       [0, 0, 5, 2]])

In [25]:
# Declara matriz identidad 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# Declara arreglo no inicializado de tres enteros
# Los valores serán lo que ya exista en esa ubicación de memoria
np.empty(3)

array([0.75, 0.75, 0.  ])

## Atributos de un `ndarray`

Cada arreglo o matriz tiene los siguientes atributos:
* `ndim`: el número de dimensiones
* `shape`: el tamaño de cada dimensión
* `size`: el tamaño total del arreglo
* `dtype`: el tipo del arreglo
* `itemsize`: el tamaño en bytes de los elementos del arreglo
* `nbytes`: el tamaño en bytes de todos los elementos del arreglo

In [27]:
# Declara semilla para reproducibilidad
np.random.seed(0) 

In [28]:
# Declara matriz 3x4x5 (m) de valores aleatorios en el intervalo [0, 10)
m = np.random.randint(10, size=(3, 4, 5)) 

# Imprime matriz m
m

array([[[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1],
        [6, 7, 7, 8, 1]],

       [[5, 9, 8, 9, 4],
        [3, 0, 3, 5, 0],
        [2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1]],

       [[9, 9, 0, 4, 7],
        [3, 2, 7, 2, 0],
        [0, 4, 5, 5, 6],
        [8, 4, 1, 4, 9]]])

In [29]:
# Imprime atributos de matriz x
print("m ndim: ", m.ndim)
print("m shape:", m.shape)
print("m size: ", m.size)
print("m dtype: ", m.dtype)
print("m itemsize: ", m.itemsize)
print("m nbytes: ", m.nbytes)

m ndim:  3
m shape: (3, 4, 5)
m size:  60
m dtype:  int64
m itemsize:  8
m nbytes:  480


## Indexación del `ndarray`

En un arreglo, se puede acceder al valor $i^{th}$ (contando desde cero) especificando el índice deseado entre corchetes, al igual que con las listas.

In [30]:
# Declara arreglo (x) de valores aleatorios en el intervalo [0, 10)
x = np.random.randint(10, size=6) 

# Imprime arreglo x
x

array([8, 1, 1, 7, 9, 9])

In [31]:
# Imprime valor en la posición 1 del arreglo x
x[0]

8

In [32]:
# Imprime valor en la posición 4 del arreglo x
x[5]

9

Para indexar desde el final del arreglo, se pueden usar índices negativos.

In [33]:
# Imprime valor en la posición n-1, donde n es el tamaño del arreglo x
x[-1]

9

In [34]:
# Imprime valor en la posición n-2, donde n es el tamaño del arreglo x
x[-2]

9

En una matriz, se puede acceder a los elementos mediante una tupla de índices separados por comas.

In [35]:
# Declara matriz 3x4 (m) de valores aleatorios en el intervalo [0, 10)
m = np.random.randint(10, size=(3, 4))

# Imprime matriz m
m

array([[3, 6, 7, 2],
       [0, 3, 5, 9],
       [4, 4, 6, 4]])

In [36]:
# Imprime valor en la posición 1 (fila), 1 (columna) de la matriz m
m[0, 0]

3

In [37]:
# Imprime valor en la posición 3 (fila), 3 (columna) de la matriz m
m[2, 2]

6

In [38]:
# Imprime valor en la posición 2 (fila), n-1 (columna), donde n es el tamaño de la matriz m
m[1, -1]

9

Los valores también se pueden modificar usando cualquiera de las notaciones anteriores.

In [39]:
# Modifica el valor en la posición 1, 1 de la matriz m
m[0, 0] = 12

# Imprime matriz m
m

array([[12,  6,  7,  2],
       [ 0,  3,  5,  9],
       [ 4,  4,  6,  4]])

A diferencia de las listas, los arreglos y matrices tienen un tipo fijo. Esto significa, por ejemplo, que si se intenta modificar un valor flotante en una matriz de enteros, el valor se truncará silenciosamente. 

In [40]:
# Modifica el valor en la posición 1, 1 por un punto flotante en la matriz m
m[0, 0] = 3.14159  

# Imprime matriz m
m

array([[3, 6, 7, 2],
       [0, 3, 5, 9],
       [4, 4, 6, 4]])

## Slicing un `ndarray`

Así como se pueden usar corchetes para acceder a elementos individuales de un arreglo o de una matriz, también se pueden usar para acceder a subarreglos con la notación de división, marcada por el carácter de dos puntos (`:`).

La sintaxis de slicing de NumPy sigue la de la lista: `x[inicio:final:step]`, y si alguno de los parámetros no se especifica, los valores predeterminados son `start=0`, `stop=tamaño de la dimensión`, `step=1`.

In [41]:
# Declara arreglo (x) con una secuencia linear en el intervalo [0, 10)
x = np.arange(10)

# Imprime arreglo x
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# Imprime valores en las primeras cinco posiciones del arreglo x
x[:5]

array([0, 1, 2, 3, 4])

In [43]:
# Imprime valores en las últimas cinco posiciones del arreglo x
x[5:] 

array([5, 6, 7, 8, 9])

In [44]:
# Imprime valores en las posiciones 5, 6 y 7 del arreglo x
x[4:7]

array([4, 5, 6])

In [45]:
# Imprime valores de cada dos posiciones del arreglo x
x[::2] 

array([0, 2, 4, 6, 8])

In [46]:
# Imprime valores de cada dos posiciones iniciando en la segunda posición del arreglo x
x[1::2]

array([1, 3, 5, 7, 9])

In [47]:
# Imprime al revés el arreglo x
x[::-1] 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [48]:
# Imprime al revés los valores de cada dos posiciones iniciando en la sexta posición del arreglo x
x[5::-2] 

array([5, 3, 1])

Las matrices funcionan de la misma manera, con varios sectores separados por comas.

In [49]:
# Declara matriz 3x4 (m) de valores aleatorios en el intervalo [0, 10)
m = np.random.randint(10, size=(3, 4))

# Imprime matriz m
m

array([[4, 3, 4, 4],
       [8, 4, 3, 7],
       [5, 5, 0, 1]])

In [50]:
# Imprime valores en las dos primeras filas y dos primeras columnas de la matriz m
m[:2, :3] 

array([[4, 3, 4],
       [8, 4, 3]])

In [51]:
# Imprime valores en las tres primeras filas de cada dos columnas de la matriz m
m[:3, ::2] 

array([[4, 4],
       [8, 3],
       [5, 0]])

In [52]:
# Imprime al revés la matriz m
m[::-1, ::-1]

array([[1, 0, 5, 5],
       [7, 3, 4, 8],
       [4, 4, 3, 4]])

Una rutina comúnmente necesaria es acceder a filas o columnas individuales de una amtriz. Esto se puede hacer combinando la indexación y el slicing, utilizando un segmento vacío marcado por el carácter de dos puntos (`:`).

In [53]:
# Imprime valores en la primer fila de la matriz m
print(m[0, :])

[4 3 4 4]


In [54]:
# Imprime valores en la primer columna de la matriz m
print(m[:, 0])

[4 8 5]


Los slices de un arreglo devuelven vistas en lugar de copias de los datos de la matriz. Este es un aspecto en el que los arreglos de NumPy difieren de las listas: en las listas, los cortes serán copias. 

In [55]:
# Extrae valores en las dos primeras filas y dos primeras columnas de la amtriz m y lo guarda en nueva matriz 2x2 (m_sub)
m_sub = m[:2, :2]

# Imprime matriz m_sub
m_sub

array([[4, 3],
       [8, 4]])

In [56]:
# Modifica el valor en la posición 1, 1 de la matriz m_sub 
m_sub[0, 0] = 100

# Imprime matriz m_sub
m_sub

array([[100,   3],
       [  8,   4]])

In [57]:
# Imprime matriz m
m

array([[100,   3,   4,   4],
       [  8,   4,   3,   7],
       [  5,   5,   0,   1]])

Se requiere de `copy()` para hacer una copia de un arreglo o una matriz y modificarlo o moodificarla de forma independiente al original.

In [58]:
# Extrae avloroes en las dos primeras filas y dos primeras columnas de la amtriz m y lo guarda en nueva matriz 2x2 (m_sub_copy)
m_sub_copy = m[:2, :2].copy()

# Imprime matriz m_sub_copy
m_sub_copy

array([[100,   3],
       [  8,   4]])

In [59]:
# Modifica el valor en la posición 1, 1 de la matriz m_sub_copy 
m_sub_copy[0, 0] = 200

# Imprime matriz m_sub
m_sub_copy

array([[200,   3],
       [  8,   4]])

In [60]:
# Imprime matriz m
m

array([[100,   3,   4,   4],
       [  8,   4,   3,   7],
       [  5,   5,   0,   1]])

## Reshaping un `ndarray`

Otro tipo útil de operación en los arreglos es el reshaping. La forma más flexible de hacerlo es con `reshape`. Y siempre que sea posible, `reshape` utilizará una vista sin copia de la matriz inicial.

In [61]:
# Declara arreglo (x) con una secuencia linear en el intervalo [0, 9)
x = np.arange(9)

# Imprime arreglo x
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
# Reformatea arreglo x en nueva matriz 3x3 (m)
m = x.reshape((3, 3))

# Imprime matriz m
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Se debe tener en cuenta que para que un reshape pueda ejecturse, el tamaño del arreglo o de la matriz inicial debe coincidir con el tamaño del arreglo o de la matriz reformateada. 

Otro patrón de reshape común es la conversión de un arreglo en una matriz bidimensional de filas o columnas. Esto se puede hacer con el método fácilmente usando la palabra clave `newaxis` dentro de una operación de slicing.

In [63]:
# Declara arreglo (x) 
x = np.array([1, 2, 3])

# Imprime arreglo x
x

array([1, 2, 3])

In [64]:
# Reformatea arreglo x en nueva matriz 1x1x3 (m)
m = x.reshape((1, 3))

# Imprime matriz m
m

array([[1, 2, 3]])

In [65]:
# Reformatea arreglo x en nueva matriz 1x1x3 (m)
m = x[np.newaxis, :]

# Imprime matriz m
m

array([[1, 2, 3]])

In [66]:
# Reformatea arreglo x en nueva matriz 1x3x1 (m)
m = x[:, np.newaxis]

# Imprime matriz m
m

array([[1],
       [2],
       [3]])

## Concatenando un `ndarray`

La concatenación, o unión de dos arreglos o matrices, se logra principalmente mediante  `np.concatenate`, `np.vstack` y `np.hstack`.

 `np.concatenate` toma una tupla o lista de matrices como primer argumento.

In [67]:
# Declara arreglo (x) 
x = np.array([1, 2, 3])

# Imprime arreglo x
x

array([1, 2, 3])

In [68]:
# Declara arreglo (y)
y = np.array([3, 2, 1])

# Imprime arreglo y
y

array([3, 2, 1])

In [69]:
# Concatena arreglo x y arreglo y
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [70]:
# Declara arreglo (z)
z = np.array([99, 99, 99])

# Imprime arreglo z
z

array([99, 99, 99])

In [71]:
# Concatena arreglo x, arreglo y y arreglo z
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [72]:
# Declara matriz 2X3 (m)
m = np.array([[1, 2, 3], 
              [4, 5, 6]])

# Imprime matriz m
m

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# Concatena dos arreglos bidimencionales en el eje vertical
np.concatenate([m, m], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
# Concatena dos arreglos bidimencionales en el eje hoorizontal
np.concatenate([m, m], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Para trabajar con concatenaciones de arreglos o matrices de dimensiones mixtas, se utiliza `np.vstack` (pila vertical) y `np.hstack` (pila horizontal).

In [75]:
# Apila verticalmente arreglo x y matriz m verticalmente
np.vstack([x, m])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [76]:
# Declara arreglo (a)
a = np.array([[2], 
              [2]])

# Imprime arreglo a
a

array([[2],
       [2]])

In [77]:
# Apila verticalmente arreglo x y matriz m horizontalmente
np.hstack([m, a])

array([[1, 2, 3, 2],
       [4, 5, 6, 2]])

## Dividiendo un `ndarray`

Lo opuesto a la concatenación es la división, que se implementa mediante `np.split`, `np.hsplit` y `np.vsplit`.

In [78]:
# Declara arreglo (x) 
x = [1, 2, 3, 99, 99, 3, 2, 1]

# Imprime arreglo x
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [79]:
# Divide arreglo x en tres nuevos arreglos (x1, x2, x3) haciendo cortes después del valor después de la posición 0 y de la posición 3
x1, x2, x3 = np.split(x, [1, 3])

# Imprime arreglo x1, x2 y x3
print(x1, x2, x3)

[1] [2 3] [99 99  3  2  1]


In [80]:
# Declara matriz 2x4 (m) con una secuencia linear en el intervalo [0, 16)
m = np.arange(16).reshape((4, 4))

# Imprime matriz m
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
# Divide matriz m en dos nuevas matrices (upper_m, lower_m) haciendo un corte después del valor después de la fila 2
upper_m, lower_m = np.vsplit(m, [2])

# Imprime matrices upper_m y lower_m
print(upper_m, "\n")
print(lower_m)

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]


In [82]:
# Divide matriz m en dos nuevas matrices (upper_m, lower_m) haciendo un corte después del valor después de la columna 2
left_m, right_m = np.hsplit(m, [2])

# Imprime matrices upper_m y lower_m
print(left_m, "\n")
print(right_m)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## Ejercicios

1. Declara un arreglo de NumPy (n) de strings con los primeros 1000 múltiplos de 42. 
2. ¿Cuál es el 360vo múltiplo de 42?
3. Declara un arreglo de NumPy de 5x6x6 (n2) de enteros aleatorios entre 1 y 100 (ambos inclusivos).
4. ¿Cuál es el total de bytes que representa n2?
5. Guarda una copia de n2 (n3) con únicamente los valores en filas y columnas pares de las segunda y tercera matriz. 
6. Concatena horizontalmente las matrices que componen n3 y guarda la nueva matriz como n4. 
7. Convierte n4 en una matriz de dos columnas y guarda la nueva matriz como n5. 
8. Suma todos los valores de n5.